### ISSUE TITLE
[Error] java.lang.NumberFormatException

### ISSUE THREAD

**Issue by mibby** [Norbo11/UltimateCards#3]
```
[07:45:59] [Server thread/INFO]: mibby issued server command: /table sit poker 1000
[07:45:59] [Server thread/WARN]: java.lang.NumberFormatException
[07:45:59] [Server thread/WARN]:    at com.github.norbo11.util.NumberMethods.getInteger(NumberMethods.java:30)
[07:45:59] [Server thread/WARN]:    at com.github.norbo11.util.NumberMethods.getPositiveInteger(NumberMethods.java:35)
[07:45:59] [Server thread/WARN]:    at com.github.norbo11.commands.table.TableSit.conditions(TableSit.java:40)
[07:45:59] [Server thread/WARN]:    at com.github.norbo11.commands.PluginExecutor.performCommand(PluginExecutor.java:219)
[07:45:59] [Server thread/WARN]:    at com.github.norbo11.commands.PluginExecutor.onCommand(PluginExecutor.java:167)
[07:45:59] [Server thread/WARN]:    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[07:45:59] [Server thread/WARN]:    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[07:45:59] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
[07:45:59] [Server thread/WARN]:    at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
[07:45:59] [Server thread/WARN]:    at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
[07:45:59] [Server thread/WARN]:    at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[07:45:59] [Server thread/WARN]:    at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[07:45:59] [Server thread/WARN]:    at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[07:45:59] [Server thread/WARN]:    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[07:45:59] [Server thread/WARN]:    at java.util.concurrent.FutureTask.run(Unknown Source)
[07:45:59] [Server thread/WARN]:    at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[07:45:59] [Server thread/WARN]:    at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
[07:45:59] [Server thread/WARN]:    at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[07:45:59] [Server thread/WARN]:    at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[07:45:59] [Server thread/WARN]:    at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[07:45:59] [Server thread/WARN]:    at java.lang.Thread.run(Unknown Source)
```

Table sit 1 1000 seems to work. Just not with the word poker or bj to join a random table. Version 1.3.6.

**Comment by mibby** [comment]
Similar error with a different command. 
http://paste.ubuntu.com/10715926/
